networks:
  default:
    external: true
      name: roboshop

services:
  mongodb:
    image: mongodb:1
    container_name: mongodb
    networks:
      - roboshop
  catalogue:
    image: catalogue:1
    container_name: catalogue
    networks:
      - roboshop

  web:
    image: web:1
    container_name: web
    ports:
      - 80:80
    networks:
      - roboshop
